spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://priyanshu-fitness.duckdns.org/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service-exact
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users
        - id: user-service-sub
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: activity-service-exact
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities
        - id: activity-service-sub
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**
        - id: ai-service-exact
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations
        - id: ai-service-sub
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8080
