spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/fitness_userdb
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8081

eureka:
    instance:
        prefer-ip-address: true
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/